name: animated_options_bar
description: A reusable animated tabbar/scrollbar component with smooth selection animations for Flutter.
version: 0.1.1
homepage: https://github.com/evilHazzarD/animated_options_bar
repository: https://github.com/evilHazzarD/animated_options_bar

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
